setwd("C:/Users/naman/Desktop/LECTURES/LECTURES-sem5/dm/Experiment 4")
x<- runif(100,0,10)
y<- 5+6*x+rnorm(100)
plot(x,y)
?lm
d<- lm(y~x)
str(d)
print(d)
par(mfrow=c(2,2))
plot(d)
ypred <- predict(d)
par(mfrow=c(1.1))
plot(y,y, type = "l",xlab = "true y", ylab = "predicted y")
points(y,ypred)
d1<- summary(d)
print(d1)
cat("OLS gave slope of ", d1$coefficients[2,1],
    "and an R-sqr of ", d1$r.squared, "\n")
x1 <- runif(100)
y1 = 5 + 6*x1 + 0.1*x1*x1 + rnorm(100)
m <- lm(y1 ~ x1)
x2 <- runif(100)
y2 = 5 + 6*x2 + 0.1*x2*x2 + rnorm(100, mean=10,sd=15)
y2pred <- predict(m,data.frame(x2))
plot(y2,y2, type = "l",xlab = "true y", ylab = "predicted y")
points(y2,y2pred)
d1<- summary(d)
print(d1)
cat("OLS gave slope of ", d1$coefficients[2,1],
    "and an R-sqr of ", d1$r.squared, "\n")

